---
title: "FFC_Stats"
author: "Alex Smith"
date: "6/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(vegan)
library(gt)
library(stargazer)

# read in data
final_data = read_csv("~/FungalFightClub/Data/finaldata1.csv")
final_data_sin = final_data[final_data$cont_ID=="s",]
final_data_sin = final_data_sin[,c(1:4,7,8)]
final_data_sin = gather(final_data_sin, "key", "value", -Plate_ID, -Fun_ID, -cont_ID, -PH_ID)
final_data_sin$PH_ID = as.factor(final_data_sin$PH_ID)
final_data_sin$Fun_ID = as.factor(final_data_sin$Fun_ID)

final_data_svs = final_data[final_data$cont_ID=="v",]
final_data_svs = final_data_svs[,c(1:4,7,8)]
final_data_svs = gather(final_data_svs, "key", "value", -Plate_ID, -Fun_ID, -cont_ID, -PH_ID)

final_data_eoc = read_csv("~/FungalFightClub/Data/final_data_eoc.csv")
final_data_eoc = final_data_eoc[final_data_eoc$cont_ID!="s",]
final_data_eoc$PH_ID = as.factor(final_data_eoc$PH_ID)
final_data_eoc$opp_ID = as.factor(final_data_eoc$opp_ID)

# constants
fungi = c("A","C","H","L","P")
pH = c(5,7)
value = c("r","K")
```

#Stats
```{r stats}
# ANOVAs for growth measures effected by pH
summary.aov(aov(value~PH_ID, data = final_data_sin[final_data_sin$key=="r",]))
summary.aov(aov(value~PH_ID, data = final_data_svs[final_data_svs$key=="r",]))

# linear model for EOC
stargazer(lm(mean_r~Fun_ID*PH_ID*opp_ID, data = final_data_eoc), 
          # out = "lmeocr.htm",
          type = "text",
          dep.var.labels = c("Growth Rate"),
          summary = TRUE,
          digits = 3
)

# stats for sin plot
Tuk_rsin = TukeyHSD(aov(lm(value~PH_ID*Fun_ID, data=final_data_sin[final_data_sin$key=="r",])))
Tuk_rsin = as.data.frame((Tuk_rsin[[3]]))
Tuk_rsin = Tuk_rsin[Tuk_rsin$`p adj`<=0.05,]
Tuk_rsin = Tuk_rsin %>% 
    mutate(pair = rownames(Tuk_rsin)) %>% 
    select(pair, diff, lwr, upr, `p adj`) %>% 
    mutate(fun=substr(pair,3,3), opp=substr(pair,7,7))
Tuk_rsin_fin = Tuk_rsin[Tuk_rsin$fun==Tuk_rsin$opp,]
Tuk_rsin_fin$key = "r"

Tuk_sin_fin = rbind(Tuk_rsin_fin)
# write_csv(Tuk_sin_fin, "~/FungalFightClub/Tuk_sin_fin.csv")

# stats for kite plot
final_data_kite = rbind(final_data_sin,final_data_svs)
Tuk_kite5 = TukeyHSD(aov(lm(value~cont_ID*Fun_ID, data=final_data_kite[final_data_kite$key=="r"&final_data_kite$PH_ID==5,])))
Tuk_kite5 = as.data.frame((Tuk_kite5[[3]]))
Tuk_kite5 = Tuk_kite5[Tuk_kite5$`p adj`<=0.05,]
Tuk_kite5 = Tuk_kite5 %>% 
    mutate(pair = rownames(Tuk_kite5)) %>% 
    select(pair, diff, lwr, upr, `p adj`) %>% 
    mutate(fun=substr(pair,3,3), opp=substr(pair,7,7))
Tuk_kite5_fin = Tuk_kite5[Tuk_kite5$fun==Tuk_kite5$opp,]

Tuk_kite7 = TukeyHSD(aov(lm(value~cont_ID*Fun_ID, data=final_data_kite[final_data_kite$key=="r"&final_data_kite$PH_ID==7,])))
Tuk_kite7 = as.data.frame((Tuk_kite7[[3]]))
Tuk_kite7 = Tuk_kite7[Tuk_kite7$`p adj`<=0.05,]
Tuk_kite7 = Tuk_kite7 %>% 
    mutate(pair = rownames(Tuk_kite7)) %>% 
    select(pair, diff, lwr, upr, `p adj`) %>% 
    mutate(fun=substr(pair,3,3), opp=substr(pair,7,7))
Tuk_kite7_fin = Tuk_kite7[Tuk_kite7$fun==Tuk_kite7$opp,]

Tuk_kite_fin = rbind(Tuk_kite5_fin,Tuk_kite7_fin)
# write_csv(Tuk_kite_fin, "~/FungalFightClub/Tuk_kite_fin.csv")

# stats for gen eoc plot
Tuk_rgeoc = TukeyHSD(aov(lm(mean_r~PH_ID*Fun_ID, data=final_data_eoc)))
Tuk_rgeoc = as.data.frame((Tuk_rgeoc[[3]]))
Tuk_rgeoc = Tuk_rgeoc[Tuk_rgeoc$`p adj`<=0.05,]
Tuk_rgeoc = Tuk_rgeoc %>% 
    mutate(pair = rownames(Tuk_rgeoc)) %>% 
    select(pair, diff, lwr, upr, `p adj`) %>% 
    mutate(fun=substr(pair,3,3), opp=substr(pair,7,7))
Tuk_rgeoc_fin = Tuk_rgeoc[Tuk_rgeoc$fun==Tuk_rgeoc$opp,]
Tuk_rgeoc_fin$key = "r"

Tuk_geoc_fin = rbind(Tuk_rgeoc_fin)
# write_csv(Tuk_geoc_fin, "~/FungalFightClub/Tuk_geoc_fin.csv")

# stats for svs and eoc plots
for(i in 1:length(fungi)){
  
  # find significant differences in EOC r values between pH conditions
  Tuk_reoc = TukeyHSD(aov(lm(mean_r~PH_ID*opp_ID, data=final_data_eoc[final_data_eoc$Fun_ID==fungi[i],])))
  Tuk_reoc = as.data.frame(Tuk_reoc[[3]])
  Tuk_reoc = Tuk_reoc[Tuk_reoc$`p adj`<=0.05,]
  Tuk_reoc = Tuk_reoc %>% 
    mutate(Fun = fungi[i], pair = rownames(Tuk_reoc)) %>% 
    select(Fun, pair, diff, lwr, upr, `p adj`) %>% 
    mutate(p1.f=substr(pair,3,3), p1.pH=substr(pair,1,1), p2.f=substr(pair,7,7), p2.pH=substr(pair,5,5))
  Tuk_reoc_fin = Tuk_reoc[Tuk_reoc$p1.f==Tuk_reoc$p2.f,]
  if(i==1){
    sig_reoc_fin = Tuk_reoc_fin
  }
  else{
    sig_reoc_fin = rbind(sig_reoc_fin,Tuk_reoc_fin)
  }
  
  # find significant differences in r values between controls and fungi in competition
  Tuk_rsvs = TukeyHSD(aov(lm(r~PH_ID*opp_ID, data=final_data_eoc[final_data_eoc$Fun_ID==fungi[i],])))
  Tuk_rsvs = as.data.frame(Tuk_rsvs[[3]])
  Tuk_rsvs = Tuk_rsvs[Tuk_rsvs$`p adj`<=0.05,]
  Tuk_rsvs = Tuk_rsvs %>% 
    mutate(Fun = fungi[i], pair = rownames(Tuk_rsvs)) %>% 
    select(Fun, pair, diff, lwr, upr, `p adj`) %>% 
    mutate(p1.f=substr(pair,3,3), p1.pH=substr(pair,1,1), p2.f=substr(pair,7,7), p2.pH=substr(pair,5,5))
  Tuk_rsvs_fin = Tuk_rsvs[(Tuk_rsvs$p1.f==fungi[i] | Tuk_rsvs$p2.f==fungi[i]),]
  if(i==1){
    sig_svs_fin_r = Tuk_rsvs_fin
  }
  else{
    sig_svs_fin_r = rbind(sig_svs_fin_r,Tuk_rsvs_fin)
  }
}

# combine data
sig_reoc_fin$key = "r"
sig_eoc_fin = rbind(sig_reoc_fin)
sig_svs_fin_r$key = "r"
sig_svs_fin = rbind(sig_svs_fin_r)
Tuk_final = rbind(sig_eoc_fin, sig_svs_fin)

# write_csv(Tuk_final, "~/FungalFightClub/Tuk_final.csv")
# write_csv(sig_svs_fin, "~/FungalFightClub/sig_svs_fin.csv")
# write_csv(sig_eoc_fin, "~/FungalFightClub/sig_eoc_fin.csv")

# create TukeyHSD results tables
sig_sin_cont = Tuk_rsin_fin[,c(6,2:5)]
colnames(sig_sin_cont) = c("Fungi", "Mean Difference", "Lower Bound", "Upper Bound", "Significance")
Tuk_sincont_table = sig_sin_cont %>% 
  gt() %>% 
  cols_align(
    align = "center",
    columns = everything()
  )
# gtsave(Tuk_sincont_table, "Tuk_sincont_table.htm")
Tuk_sincont_table

sig_svs_cont = sig_svs_fin[sig_svs_fin$p1.f==sig_svs_fin$p2.f&sig_svs_fin$p2.f==sig_svs_fin$Fun,]
sig_svs_cont = sig_svs_cont[c(1,2),c(1,3:6)]
colnames(sig_svs_cont) = c("Fungi", "Mean Difference", "Lower Bound", "Upper Bound", "Significance")
Tuk_svscont_table = sig_svs_cont %>% 
  gt() %>% 
  cols_align(
    align = "center",
    columns = everything()
  )
# gtsave(Tuk_svscont_table, "Tuk_svscont_table.htm")
Tuk_svscont_table

sig_gen_eoc = Tuk_rgeoc_fin[,c(6,2:5)]
colnames(sig_gen_eoc) = c("Fungi", "Mean Difference", "Lower Bound", "Upper Bound", "Significance")
Tuk_geoc_table = sig_gen_eoc %>% 
  gt() %>% 
  cols_align(
    align = "center",
    columns = everything()
  )
# gtsave(Tuk_geoc_table, "Tuk_geoc_table.htm")
Tuk_geoc_table

sig_eoc_fin = sig_reoc_fin[,c(1,7,3:6)]
colnames(sig_eoc_fin) = c("Fungi", "Opponent", "Mean Difference", "Lower Bound", "Upper Bound", "Significance")
Tuk_eocphdiff_table = sig_eoc_fin %>% 
  gt() %>% 
  cols_align(
    align = "center",
    columns = everything()
  )
# gtsave(Tuk_eocphdiff_table, "Tuk_eocphdiff_table.htm")
Tuk_eocphdiff_table

sig_svs_fin = sig_svs_fin[sig_svs_fin$p1.pH==sig_svs_fin$p2.pH,]
sig_svs_fin$p1.f = ifelse(sig_svs_fin$Fun==sig_svs_fin$p1.f, sig_svs_fin$p2.f, sig_svs_fin$p1.f)
sig_svs_fin = sig_svs_fin[c(1:21),c(1,7,8,3:6)]
colnames(sig_svs_fin) = c("Fungi", "Opponent", "pH", "Mean Difference", "Lower Bound", "Upper Bound", "Significance")
Tuk_svsdiff_table = sig_svs_fin %>% 
  gt() %>% 
  cols_align(
    align = "center",
    columns = everything()
  )
# gtsave(Tuk_svsdiff_table, "Tuk_svsdiff_table.htm")
Tuk_svsdiff_table
```
