---
title: "FFC_Plots"
author: "Alex Smith"
date: "6/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Rmisc)
library(tidyverse)
library(cowplot)
library(visNetwork)
library(ape)
library(ggpubr)
library(lme4)
library(lmerTest)
library(MuMIn)
library(emmeans)
library(stargazer)
library(ggeffects)

# read in data
final_data = read_csv("~/FungalFightClub/finaldata1.csv")
final_data_sin = final_data[final_data$cont_ID=="s",]
final_data_eoc = read_csv("~/FungalFightClub/final_data_eoc.csv")
final_data_eoc$PH_ID = as.character(final_data_eoc$PH_ID) # to fix code
final_data_eoc$Plug_ID = substr(final_data_eoc$Plug_ID,1,4) # to fix code
Tuk_sin_fin = read_csv("~/FungalFightClub/Tuk_sin_fin.csv")
Tuk_geoc_fin = read_csv("~/FungalFightclub/Tuk_geoc_fin.csv")
Tuk_final = read_csv("~/FungalFightClub/Tuk_final.csv")
sig_svs_fin = read_csv("~/FungalFightClub/sig_svs_fin.csv")
sig_eoc_fin = read_csv("~/FungalFightClub/sig_eoc_fin.csv")
net_rt = read_csv("~/FungalFightClub/FFC Treatments - Reaction Types.csv")
FFC_nex = read.nexus("~/FungalFightClub/infile.nex.con.tre")
FFC_nexbay = read.nexus("~/FungalFightClub/mrBayesPost.nex")
FFC_nexrax = read.nexus("~/FungalFightClub/RAxML_Tree.nex")
ffc_n_pair = read_csv("~/FungalFightClub/ffc_n_pair.csv")

# constants
fungi = c("A","C","H","L","P")
pH = c(5,7)
value = c("r","K")

# labels
labs = data.frame(main=c("(a) Amanita muscaria","(b) Cenococcum geophilum","(c) Hebeloma cylindrosporum","(d) Laccaria bicolor","(e) Paxillus involutus"), letter=c("(a)","(b)","(c)","(d)","(e)"), nams=c("A. muscaria","C. geophilum","H. cylindrosporum","L. bicolor","P. involutus"), x=c(-0.055,-0.0725,-0.0775,-0.05,-0.055), y=c(1,1,1,1,1))

# color palette
palette = c("#EC8FA3", "#FCBA65", "#FAECCF", "#8D7F99", "#8C9D57")
```

#Sin Plot
```{r sin}
# create sin only df
final_data_sinp = final_data_sin[,c(1:4,7,8)]
final_data_sinp = gather(final_data_sinp, "key", "value", -Plate_ID, -Fun_ID, -cont_ID, -PH_ID)
final_data_sinp$PH_ID = as.factor(final_data_sinp$PH_ID)

# configure stat labels
Tuk_sin_fin = Tuk_sin_fin[,c(6,5,8)]
Tuk_sin_fin$sig = ifelse(0.01<Tuk_sin_fin$`p adj`&Tuk_sin_fin$`p adj`<=0.05,"*",
                ifelse(0.001<Tuk_sin_fin$`p adj`&Tuk_sin_fin$`p adj`<=0.01,"**","***"))
Tuk_sin_fin$x = c(0.8,1.8,2.8,0.8,1.8,2.8,3.8)
Tuk_sin_fin$xend = c(1.2,2.2,3.2,1.2,2.2,3.2,4.2)
Tuk_sin_fin$y = c(0.28,0.2,0.32,16,10,20,17)
Tuk_sin_fin$xlab = c(1,2,3,1,2,3,4)
Tuk_sin_fin$ylab = c(0.29,0.21,0.33,16.5,10.5,20.5,17.5)

# plot growth rate of sin
sinplot_r = ggplot(final_data_sinp[final_data_sinp$key=="r",], aes(Fun_ID, value)) + 
    theme_cowplot() +
    geom_boxplot(outlier.alpha = 0, aes(fill=PH_ID), color="black", width=0.75) +
    geom_point(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.9), aes(Fun_ID,value,fill = PH_ID,alpha=0.7)) +
    ylab(bquote('growth rate ('*cm^2*'/day)')) +
    scale_x_discrete(labels = labs$nams) +
    geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype=2, size=0.25) +
    geom_segment(data = Tuk_sin_fin[1:3,], aes(x=x,xend=xend,y=y,yend=y),color = "black") + 
    geom_text(data = Tuk_sin_fin[1:3,], aes(xlab, ylab, label = sig)) +
    theme(legend.position = "none", axis.line.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.margin = unit(c(1,0,1,1), "cm"), axis.text.x = element_text(face="italic", angle=330, size=10), axis.title.y = element_text(size = 11), plot.background = element_rect(fill = "white"))
# ggsave("sinplot_r.png", width = 7, height = 5)

# plot colony size of sin
sinplot_K = ggplot(final_data_sinp[final_data_sinp$key=="K",], aes(Fun_ID, value)) + 
    theme_cowplot() +
    geom_boxplot(outlier.alpha = 0, aes(fill=PH_ID), color="black", width=0.75) +
    geom_point(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.9), aes(Fun_ID,value,fill = PH_ID,alpha=0.7)) +
    ylab(bquote('colony size ('*cm^2*')')) +
    scale_x_discrete(labels = labs$nams) +
    geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype=2, size=0.25) +
    geom_segment(data = Tuk_sin_fin[4:7,], aes(x=x,xend=xend,y=y,yend=y),color = "black") + 
    geom_text(data = Tuk_sin_fin[4:7,], aes(xlab, ylab, label = sig)) +
    theme(legend.position = "none", axis.line.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.margin = unit(c(1,0,1,1), "cm"), axis.text.x = element_text(face="italic", angle=330, size=10), axis.title.y = element_text(size = 11), plot.background = element_rect(fill = "white"))
# ggsave("sinplot_K.png", width = 7, height = 5)

sinplot_r
sinplot_K
```

#Svs Plot
```{r svs}
# create svs only df
final_data_svs = final_data_eoc[final_data_eoc$cont_ID=="v",c(1:4,7,8)]
final_data_svs = gather(final_data_svs, "key", "value", -Plate_ID, -Fun_ID, -cont_ID, -PH_ID)

# take control only stats and configure stat labels
Tuk_final = Tuk_final[Tuk_final$p1.f==Tuk_final$p2.f&Tuk_final$p2.f==Tuk_final$Fun,]
Tuk_final$sig = ifelse(0.01<Tuk_final$`p adj`&Tuk_final$`p adj`<=0.05,"*",
                ifelse(0.001<Tuk_final$`p adj`&Tuk_final$`p adj`<=0.01,"**","***"))
Tuk_final$x = c(1.8,2.8,1.8,2.8,3.8) #3.8,4.8,
Tuk_final$xend = c(2.2,3.2,2.2,3.2,4.2) #4.2,5.2,
Tuk_final$y = c(0.2,0.3,7,12,10) #0.27,0.32,
Tuk_final$xlab = c(2,3,2,3,4) #4,5,
Tuk_final$ylab = c(0.21,0.31,7.5,12.5,10.5) #0.28,0.33,

# plot growth rate of svs
svsplot_r = ggplot(final_data_svs[final_data_svs$key=="r",], aes(Fun_ID, value)) + 
    theme_cowplot() +
    geom_boxplot(outlier.alpha = 0, aes(fill=PH_ID), color="black", width=0.75) +
    geom_point(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.9), aes(Fun_ID,value,fill = PH_ID,alpha=0.7)) +
    ylab(bquote('growth rate ('*cm^2*'/day)')) +
    scale_x_discrete(labels = labs$nams) +
    geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype=2, size=0.25) +
    geom_segment(data = Tuk_final[1:2,], aes(x=x,xend=xend,y=y,yend=y),color = "black") + 
    geom_text(data = Tuk_final[1:2,], aes(xlab, ylab, label = sig)) +
    theme(legend.position = "none", axis.line.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.margin = unit(c(1,0,1,1), "cm"), axis.text.x = element_text(face="italic", angle=330, size=10), axis.title.y = element_text(size = 11))
# ggsave("svsplot_r.png", width = 7, height = 5)

# plot colony size of svs
svsplot_K = ggplot(final_data_svs[final_data_svs$key=="K",], aes(Fun_ID, value)) + 
    theme_cowplot() +
    geom_boxplot(outlier.alpha = 0, aes(fill=PH_ID), color="black", width=0.75) +
    geom_point(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.9), aes(Fun_ID,value,fill = PH_ID,alpha=0.7)) +
    ylab(bquote('colony size ('*cm^2*')')) +
    scale_x_discrete(labels = labs$nams) +
    geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype=2, size=0.25) +
    geom_segment(data = Tuk_final[3:5,], aes(x=x,xend=xend,y=y,yend=y),color = "black") + 
    geom_text(data = Tuk_final[3:5,], aes(xlab, ylab, label = sig)) +
    theme(legend.position = "none", axis.line.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.margin = unit(c(1,0,1,1), "cm"), axis.text.x = element_text(face="italic", angle=330, size=10), axis.title.y = element_text(size = 11))
# ggsave("svsplot_K.png", width = 7, height = 5)

svsplot_r
svsplot_K
```

```{r kite plot}
col00 <- "#FAE093"
colL0 <- "#CABEE9"
col0B <- "#D04E59"
colLB <- "#7C7189"
colset <- c('#D04E59','#FAE093','#7C7189','#CABEE9')

final_data_cont = final_data[final_data$cont_ID != 0,]
final_cont_sum = summarySE(data=final_data_cont, "r", groupvars = c("Fun_ID", "cont_ID", "PH_ID"))
names(final_cont_sum)[which(names(final_cont_sum)=="r")] = "mean"

xcenter = c(5,10,15,20,25)
xcoords.L = c(4,9,14,19,24)
xcoords.R = c(6,11,16,21,26)
xcoords = sort(c(xcoords.L,xcoords.R))

png("kiteplot.png",width=9,height=6,units="in",res=200)

plot(xcoords,final_cont_sum[final_cont_sum$PH_ID==7,]$mean,xlab='',ylab=expression('growth rate (cm'^'2'~'/day)'),las=1,ylim=c(min(final_cont_sum$mean-final_cont_sum$se)*1.05,max(final_cont_sum$mean+final_cont_sum$se)*1.25),type='n',xaxt='n',bty="l")

arrows(xcoords.R,final_cont_sum[final_cont_sum$PH_ID==7&final_cont_sum$cont_ID=="v",]$mean,xcoords.L,final_cont_sum[final_cont_sum$PH_ID==7&final_cont_sum$cont_ID=="s",]$mean,lwd=2,code=0,col='gray70')
arrows(xcoords.R,final_cont_sum[final_cont_sum$PH_ID==5&final_cont_sum$cont_ID=="v",]$mean,xcoords.L,final_cont_sum[final_cont_sum$PH_ID==5&final_cont_sum$cont_ID=="s",]$mean,lwd=2,code=0,col='gray70')
arrows(xcoords.R,final_cont_sum[final_cont_sum$PH_ID==5&final_cont_sum$cont_ID=="v",]$mean,xcoords.R,final_cont_sum[final_cont_sum$PH_ID==7&final_cont_sum$cont_ID=="v",]$mean,lwd=2,code=0,col='gray70')
arrows(xcoords.L,final_cont_sum[final_cont_sum$PH_ID==5&final_cont_sum$cont_ID=="s",]$mean,xcoords.L,final_cont_sum[final_cont_sum$PH_ID==7&final_cont_sum$cont_ID=="s",]$mean,lwd=2,code=0,col='gray70')

arrows(xcoords,final_cont_sum[final_cont_sum$PH_ID==7,]$mean+final_cont_sum[final_cont_sum$PH_ID==7,]$sd,xcoords,final_cont_sum[final_cont_sum$PH_ID==7,]$mean-final_cont_sum[final_cont_sum$PH_ID==7,]$sd,code=3,angle=90,length=0.08)
arrows(xcoords,final_cont_sum[final_cont_sum$PH_ID==5,]$mean+final_cont_sum[final_cont_sum$PH_ID==5,]$sd,xcoords,final_cont_sum[final_cont_sum$PH_ID==5,]$mean-final_cont_sum[final_cont_sum$PH_ID==5,]$sd,code=3,angle=90,length=0.08)

points(xcoords,final_cont_sum[final_cont_sum$PH_ID==7,]$mean,cex=1.5,pch=21,bg=c(colL0,colLB))
points(xcoords,final_cont_sum[final_cont_sum$PH_ID==5,]$mean,cex=1.5,pch=21,bg=c(col00,col0B))

axis(1,at=xcenter,labels=c(expression(italic("A. muscaria")),expression(italic("C. geophilum")),expression(italic("H. cylindrosporum")),expression(italic("L. bicolor")),expression(italic("P. involutus"))))
legend(3.5,0.35,legend=c('Single Control, pH 5.6 ','SvS Control, pH 5.6'),horiz=T,pch=21,pt.cex=1.5,pt.bg=colset[2:1],cex=1,bty='n')
legend(3.5,0.37,legend=c('Single Control, pH 7 ','SvS Control, pH 7'),horiz=T,pch=21,pt.cex=1.5,pt.bg=colset[4:3],cex=1,bty='n')

dev.off()
```

```{r eoc gen plot}
# configure stat labels
Tuk_geoc_fin = Tuk_geoc_fin[,c(6,5,8)]
Tuk_geoc_fin$sig = ifelse(0.01<Tuk_geoc_fin$`p adj`&Tuk_geoc_fin$`p adj`<=0.05,"*",
                ifelse(0.001<Tuk_geoc_fin$`p adj`&Tuk_geoc_fin$`p adj`<=0.01,"**","***"))
Tuk_geoc_fin$x = c(1.8,2.8,1.8,4.8)
Tuk_geoc_fin$xend = c(2.2,3.2,2.2,5.2)
Tuk_geoc_fin$y = c(2.4,1.4,2.5,2.3)
Tuk_geoc_fin$xlab = c(2,3,2,5)
Tuk_geoc_fin$ylab = c(2.5,1.5,2.6,2.4)

# plot gen eoc
eocgenplot_r = ggplot(final_data_eoc[final_data_eoc$cont_ID==0,], aes(Fun_ID, mean_r)) + 
    theme_cowplot() +
    geom_boxplot(outlier.alpha = 0, aes(fill=PH_ID), color="black", width=0.75) +
    geom_point(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.9), aes(Fun_ID,mean_r,fill = PH_ID,alpha=0.7)) +
    ylab(bquote('growth rate ('*cm^2*'/day)')) +
    scale_x_discrete(labels = labs$nams) +
    geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype=2, size=0.25) +
    geom_segment(data = Tuk_geoc_fin[1:2,], aes(x=x,xend=xend,y=y,yend=y),color = "black") +
    geom_text(data = Tuk_geoc_fin[1:2,], aes(xlab, ylab, label = sig)) +
    theme(legend.position = "none", axis.line.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.margin = unit(c(1,0,1,1), "cm"), axis.text.x = element_text(face="italic", angle=330, size=10), axis.title.y = element_text(size = 11))
# ggsave("eocgenplot_r.png", width = 7, height = 5)

eocgenplot_K = ggplot(final_data_eoc[final_data_eoc$cont_ID==0,], aes(Fun_ID, mean_K)) + 
    theme_cowplot() +
    geom_boxplot(outlier.alpha = 0, aes(fill=PH_ID), color="black", width=0.75) +
    geom_point(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.9), aes(Fun_ID,mean_K,fill = PH_ID,alpha=0.7)) +
    ylab(bquote('colony size ('*cm^2*')')) +
    scale_x_discrete(labels = labs$nams) +
    geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype=2, size=0.25) +
    geom_segment(data = Tuk_geoc_fin[3:4,], aes(x=x,xend=xend,y=y,yend=y),color = "black") +
    geom_text(data = Tuk_geoc_fin[3:4,], aes(xlab, ylab, label = sig)) +
    theme(legend.position = "none", axis.line.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(), plot.margin = unit(c(1,0,1,1), "cm"), axis.text.x = element_text(face="italic", angle=330, size=10), axis.title.y = element_text(size = 11))
# ggsave("eocgenplot_K.png", width = 7, height = 5)

eocgenplot_r
eocgenplot_K
```

#EOC Plot
```{r eoc, fig.height=11, fig.width=8, warning=FALSE}
# annotation df for significant difference from control
sig_svs_fin = sig_svs_fin[sig_svs_fin$p1.pH==sig_svs_fin$p2.pH,]
annot_svs = as.data.frame(sig_svs_fin[,6])
annot_svs$Fun_ID = sig_svs_fin$Fun
annot_svs$PH_ID = sig_svs_fin$p1.pH
annot_svs$pair_ID = ifelse(annot_svs$Fun_ID==sig_svs_fin$p1.f,sig_svs_fin$p2.f,sig_svs_fin$p1.f)
annot_svs$key = sig_svs_fin$key
annot_svs$sig = ifelse(0.01<annot_svs$`p adj`&annot_svs$`p adj`<=0.05,"*",
                ifelse(0.001<annot_svs$`p adj`&annot_svs$`p adj`<=0.01,"**","***"))
annot_svs$x = c(2.2,5.2,0.8,1.2,2.8,3.8,1.2,2.2,4.2,5.2,0.8,1.2,1.8,2.2,2.8,3.2,4.8,2.2,3.2,3.8,4.2,4.8,2.2,1.2,2.8,3.8,4.8,3.2,5.2,0.8,1.2,2.2,3.8,4.8,4.2,5.2,0.8,1.2,2.2,2.8,3.2,0.8,1.2,1.8,2.2,2.8,3.2,3.8,4.2)
for (i in 1:nrow(annot_svs[annot_svs$key=="r",])) {
  annot_svs$ymax[i] = max(final_data_eoc[final_data_eoc$Fun_ID==annot_svs$Fun_ID[i]&final_data_eoc$PH_ID==annot_svs$PH_ID[i]&final_data_eoc$opp_ID==annot_svs$pair_ID[i],"mean_r"])
}
for (i in (1+nrow(annot_svs[annot_svs$key=="r",])):nrow(annot_svs)) {
  annot_svs$ymax[i] = max(final_data_eoc[final_data_eoc$Fun_ID==annot_svs$Fun_ID[i]&final_data_eoc$PH_ID==annot_svs$PH_ID[i]&final_data_eoc$opp_ID==annot_svs$pair_ID[i],"mean_K"])
}
annot_svs$y = ifelse(annot_svs$key=="r", annot_svs$ymax + 0.1, annot_svs$ymax + 0.2)

# annotation df for significant difference between eoc by pH
sig_eoc_fin$sig = ifelse(0.01<sig_eoc_fin$`p adj`&sig_eoc_fin$`p adj`<=0.05,"*",
                ifelse(0.001<sig_eoc_fin$`p adj`&sig_eoc_fin$`p adj`<=0.01,"**","***"))
sig_eoc_fin$x = c(2.8,3.8,0.8,1.8,3.8,4.8,4.8,1.8,1.8,0.8,2.8,3.8,1.8,3.8,0.8,1.8,2.8,0.8,1.8,2.8,3.8)
sig_eoc_fin$xend = sig_eoc_fin$x + 0.4
for (i in 1:nrow(sig_eoc_fin[sig_eoc_fin$key=="r",])) {
  sig_eoc_fin$ymax[i] = max(final_data_eoc[final_data_eoc$Fun_ID==sig_eoc_fin$Fun[i]&final_data_eoc$opp_ID==sig_eoc_fin$p1.f[i],"mean_r"])
}
for (i in (1+nrow(sig_eoc_fin[sig_eoc_fin$key=="r",])):(nrow(sig_eoc_fin))) {
  sig_eoc_fin$ymax[i] = max(final_data_eoc[final_data_eoc$Fun_ID==sig_eoc_fin$Fun[i]&final_data_eoc$opp_ID==sig_eoc_fin$p1.f[i],"mean_K"])
}
sig_eoc_fin$y = ifelse(sig_eoc_fin$key=="r", sig_eoc_fin$ymax + 0.2, sig_eoc_fin$ymax + 0.4)
for (i in 1:nrow(sig_eoc_fin)) {
  sig_eoc_fin$xlab[i] = mean(c(sig_eoc_fin$x[i],sig_eoc_fin$xend[i]))
}
sig_eoc_fin$ylab = sig_eoc_fin$y + 0.05

eocplots = vector(mode="list", length=10) # vector for storing individual eoc plots
# create plots of eoc by r
for(i in 1:length(fungi)){
  subdat <- final_data_eoc[final_data_eoc$Fun_ID==fungi[i],]
  eocplots[[i]] = ggplot(subdat, aes(opp_ID,mean_r)) +
    theme_cowplot() +
    geom_boxplot(outlier.alpha = 0, aes(fill=PH_ID), color="black") +
    geom_point(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.9), aes(opp_ID,mean_r,fill = PH_ID,alpha=0.7)) +
    expand_limits(y=c(0.5,1.5)) +
    scale_y_continuous(breaks=c(0,0.5,1,1.5,2,2.5)) +
    geom_hline(yintercept=1, size=0.35, linetype=2) +
    geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype=2, size=0.25) +
    theme(legend.position = "none", axis.line.x = element_blank(), axis.ticks.x = element_blank(), plot.margin = unit(c(1,1,0.5,1), "cm"), axis.title.x = element_blank(), axis.text.x = element_blank()) +
    ylab("EoC")
}
# create plots of eoc by K
for(i in 1:length(fungi)){
  subdat <- final_data_eoc[final_data_eoc$Fun_ID==fungi[i],]
  eocplots[[i+5]] = ggplot(subdat, aes(opp_ID,mean_K)) +
    theme_cowplot() +
    geom_boxplot(outlier.alpha = 0, aes(fill=PH_ID), color="black") +
    geom_point(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.9), aes(opp_ID,mean_K,fill = PH_ID,alpha=0.7)) +
    scale_y_continuous(breaks=c(0,0.5,1,1.5,2,2.5,3,3.5,4)) +
    geom_hline(yintercept=1, size=0.35, linetype=2) +
    geom_vline(xintercept = c(1.5,2.5,3.5,4.5), linetype=2, size=0.25) +
    theme(legend.position = "none", axis.line.x = element_blank(), axis.ticks.x = element_blank(), plot.margin = unit(c(1,1,0.5,1), "cm"), axis.title.x = element_blank(), axis.text.x = element_blank()) +
    ylab("EoC (K)")
}

# add annotations for significant differences from control
plotnum = c(1,1,rep(2,4),rep(3,4),rep(4,7),rep(5,4),6,6,rep(7,6),rep(8,7),rep(9,5),rep(10,8))
for (i in 1:nrow(annot_svs)) {
  eocplots[[plotnum[i]]] = eocplots[[plotnum[i]]] + geom_text(data=annot_svs[i,], aes(x,y,label=sig))
}

# add annotations for significant differences between eoc by pH
plotnum1 = c(2,2,3,3,3,3,4,5,6,7,7,7,8,8,9,9,9,10,10,10,10)
for (i in 1:nrow(sig_eoc_fin)) {
  eocplots[[plotnum1[i]]] = eocplots[[plotnum1[i]]] + geom_segment(data = sig_eoc_fin[i,], aes(x=x,xend=xend,y=y,yend=y),color = "black") + geom_text(data = sig_eoc_fin[i,], aes(xlab, ylab, label = sig))
}

# add opponent ID to bottom of plots
eocplots[[5]] = eocplots[[5]] + scale_x_discrete(labels = labs$nams) + theme(axis.text.x = element_text(face="italic", angle=330, size=10))
eocplots[[10]] = eocplots[[10]] + scale_x_discrete(labels = labs$nams) + theme(axis.text.x = element_text(face="italic", angle=330, size=10))

# assemble eoc by r plot
eocplot_r=plot_grid(eocplots[[1]],eocplots[[2]],eocplots[[3]],eocplots[[4]],eocplots[[5]],nrow=5,ncol=1,labels=labs$main,label_size=14,label_x=labs$x,label_y=labs$y,rel_heights= c(1,1,1,1,1.25))
# ggsave("eocplot_r.png", height = 11, width = 8)

# assemble eoc by K plot
eocplot_K=plot_grid(eocplots[[6]],eocplots[[7]],eocplots[[8]],eocplots[[9]],eocplots[[10]],nrow=5,ncol=1,labels=labs$main,label_size=14,label_x=labs$x,label_y=labs$y,rel_heights= c(1,1,1,1,1.25))
# ggsave("eocplot_K.png", height = 11, width = 8)

eocplot_r
eocplot_K
```

#Network Plots
```{r net, fig.height=7, fig.width=7}
# get control data ready for comparison to other controls
final_data_sin1 = final_data_sinp %>% 
  spread(key = key, value = value)
final_data_sin1$Treat_ID = substr(final_data_sin1$Plate_ID,1,3)
final_data_sin1 = final_data_sin1 %>% 
  dplyr::group_by(Treat_ID) %>%
  dplyr::summarise(mean_r = mean(r, na.rm=TRUE), mean_K = mean(K, na.rm=TRUE)) %>% 
  dplyr::mutate(PH_ID = substr(Treat_ID,3,3), Fun_ID = substr(Treat_ID,1,1))
final_data_sin5 = final_data_sin1[final_data_sin1$PH_ID==5,]
final_data_sin7 = final_data_sin1[final_data_sin1$PH_ID==7,]

final_data_svs = final_data_eoc[final_data_eoc$cont_ID=="v",]
final_data_svs$Treat_ID = substr(final_data_svs$Plate_ID,1,3)
final_data_svs = final_data_svs %>% 
  dplyr::group_by(Treat_ID) %>% 
  dplyr::summarise(mean_r = mean(r, na.rm=TRUE), mean_K = mean(K, na.rm=TRUE)) %>% 
  dplyr::mutate(PH_ID = substr(Treat_ID,3,3), Fun_ID = substr(Treat_ID,1,1))
final_data_svs5 = final_data_svs[final_data_svs$PH_ID==5,]
final_data_svs7 = final_data_svs[final_data_svs$PH_ID==7,]

# set up a df for storing network control values
contpairfin = as.data.frame(matrix(nrow=25,ncol=2))
colnames(contpairfin) = c("Fun", "opp")
contpairfin$Fun = c(rep("A",5),rep("C",5),rep("H",5),rep("L",5),rep("P",5))
contpairfin$opp = c(rep(c("A","C","H","L","P"),5))
contpairfin = contpairfin[contpairfin$Fun!=contpairfin$opp,]
contpairfin5 = contpairfin
contpairfin7 = contpairfin
contsinfin5 = contpairfin
contsinfin7 = contpairfin

# calculate the control comparison (which will be the width of network lines)
for (x in 1:nrow(contsinfin5)) {
  contsinfin5$width_r[x] = (final_data_sin5[final_data_sin5$Fun_ID==contsinfin5$Fun[x],"mean_r"])/(final_data_sin5[final_data_sin5$Fun_ID==contsinfin5$opp[x],"mean_r"])
  contsinfin5$width_K[x] = (final_data_sin5[final_data_sin5$Fun_ID==contsinfin5$Fun[x],"mean_K"])/(final_data_sin5[final_data_sin5$Fun_ID==contsinfin5$opp[x],"mean_K"])
}
value_cs5r = rep(1,5)
value_cs5K = rep(1,5)
for (x in 1:5) {
  value_cs5r[x] = sum(unlist(contsinfin5$width_r[contsinfin5$Fun==fungi[x]]))
  value_cs5K[x] = sum(unlist(contsinfin5$width_K[contsinfin5$Fun==fungi[x]]))
}

for (x in 1:nrow(contsinfin7)) {
  contsinfin7$width_r[x] = (final_data_sin7[final_data_sin7$Fun_ID==contsinfin7$Fun[x],"mean_r"])/(final_data_sin7[final_data_sin7$Fun_ID==contsinfin7$opp[x],"mean_r"])
  contsinfin7$width_K[x] = (final_data_sin7[final_data_sin7$Fun_ID==contsinfin7$Fun[x],"mean_K"])/(final_data_sin7[final_data_sin7$Fun_ID==contsinfin7$opp[x],"mean_K"])
}
value_cs7r = rep(1,5)
value_cs7K = rep(1,5)
for (x in 1:5) {
  value_cs7r[x] = sum(unlist(contsinfin7$width_r[contsinfin7$Fun==fungi[x]]))
  value_cs7K[x] = sum(unlist(contsinfin7$width_K[contsinfin7$Fun==fungi[x]]))
}

for (x in 1:nrow(contpairfin5)) {
  contpairfin5$width_r[x] = (final_data_svs5[final_data_svs5$Fun_ID==contpairfin5$Fun[x],"mean_r"])/(final_data_svs5[final_data_svs5$Fun_ID==contpairfin5$opp[x],"mean_r"])
  contpairfin5$width_K[x] = (final_data_svs5[final_data_svs5$Fun_ID==contpairfin5$Fun[x],"mean_K"])/(final_data_svs5[final_data_svs5$Fun_ID==contpairfin5$opp[x],"mean_K"])
}
value_cp5r = rep(1,5)
value_cp5K = rep(1,5)
for (x in 1:5) {
  value_cp5r[x] = sum(unlist(contpairfin5$width_r[contpairfin5$Fun==fungi[x]]))
  value_cp5K[x] = sum(unlist(contpairfin5$width_K[contpairfin5$Fun==fungi[x]]))
}

for (x in 1:nrow(contpairfin7)) {
  contpairfin7$width_r[x] = (final_data_svs7[final_data_svs7$Fun_ID==contpairfin7$Fun[x],"mean_r"])/(final_data_svs7[final_data_svs7$Fun_ID==contpairfin7$opp[x],"mean_r"])
  contpairfin7$width_K[x] = (final_data_svs7[final_data_svs7$Fun_ID==contpairfin7$Fun[x],"mean_K"])/(final_data_svs7[final_data_svs7$Fun_ID==contpairfin7$opp[x],"mean_K"])
}
value_cp7r = rep(1,5)
value_cp7K = rep(1,5)
for (x in 1:5) {
  value_cp7r[x] = sum(unlist(contpairfin7$width_r[contpairfin7$Fun==fungi[x]]))
  value_cp7K[x] = sum(unlist(contpairfin7$width_K[contpairfin7$Fun==fungi[x]]))
}

# network of sin controls pH 5 for r
nodes = data.frame(id = 1:5, value = value_cs5r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contsinfin5$width_r),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

sin5r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# sin5r

# network of sin controls pH 7 for r
nodes = data.frame(id = 1:5, value = value_cs7r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contsinfin7$width_r),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

sin7r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# sin7r

# network of sin controls pH 5 for K
nodes = data.frame(id = 1:5, value = value_cs5K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contsinfin5$width_K),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

sin5K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# sin5K

# network of sin controls pH 7 for K
nodes = data.frame(id = 1:5, value = value_cs7K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contsinfin7$width_K),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

sin7K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# sin7K

# network of svs controls pH 5 for r
nodes = data.frame(id = 1:5, value = value_cp5r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contpairfin5$width_r),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

cont5r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# cont5r

# network of svs controls pH 7 for r
nodes = data.frame(id = 1:5, value = value_cp7r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contpairfin7$width_r),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

cont7r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# cont7r

# network of svs controls pH 5 for K
nodes = data.frame(id = 1:5, value = value_cp5K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contpairfin5$width_K),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

cont5K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# cont5K

# network of svs controls pH 7 for K
nodes = data.frame(id = 1:5, value = value_cp7K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contpairfin7$width_K),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

cont7K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# cont7K

# eoc wins
eocnetwin = final_data_eoc[final_data_eoc$cont_ID==0,] %>% 
  dplyr::group_by(Plate_ID) %>% 
  dplyr::mutate(eocrwin = Plug_ID[which.max(mean_r)],
                eocKwin = Plug_ID[which.max(mean_K)])

eocnetwinr = as.data.frame(base::table(eocnetwin[eocnetwin$cont_ID==0,"eocrwin"]))
eocnetwinK = as.data.frame(base::table(eocnetwin[eocnetwin$cont_ID==0,"eocKwin"]))
eocnetwinr$Freq = eocnetwinr$Freq/2
eocnetwinK$Freq = eocnetwinK$Freq/2
eocnetwinr$PH = substr(eocnetwinr$Var1,4,4)
eocnetwinK$PH = substr(eocnetwinK$Var1,4,4)
eocnetwinr$Fun = toupper(substr(eocnetwinr$Var1,1,1))
eocnetwinK$Fun = toupper(substr(eocnetwinK$Var1,1,1))


# eoc 5 r
eoc5rfin = eocnetwinr[eocnetwinr$PH==5,]
value_e5r = rep(1,5)
for (x in 1:5) {
  value_e5r[x] = sum(unlist(eoc5rfin$Freq[eoc5rfin$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_e5r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(0,4,6,10,10,8,5,8,6,0,10,6,4,0,0,2,0,1,4,8),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width/1.5

eoc5r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# eoc5r

# eoc 7 r
eoc7rfin = eocnetwinr[eocnetwinr$PH==7,]
value_e7r = rep(1,5)
for (x in 1:5) {
  value_e7r[x] = sum(unlist(eoc7rfin$Freq[eoc7rfin$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_e7r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(5,6,9,10,4,9,9,10,0,0,1,1,0,0,7,8,0,0,9,2),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width/1.5

eoc7r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# eoc7r

# eoc 5 K
eoc5Kfin = eocnetwinK[eocnetwinK$PH==5,]
value_e5K = rep(1,5)
for (x in 1:5) {
  value_e5K[x] = sum(unlist(eoc5Kfin$Freq[eoc5Kfin$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_e5K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(7,1,4,9,3,7,4,0,9,1,10,3,6,1,0,2,1,9,7,8),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width/1.5

eoc5K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# eoc5K

# eoc 7 K
eoc7Kfin = eocnetwinK[eocnetwinK$PH==7,]
value_e7K = rep(1,5)
for (x in 1:5) {
  value_e7K[x] = sum(unlist(eoc7Kfin$Freq[eoc7Kfin$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_e7K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(9,0,1,10,0,0,0,0,6,9,8,10,8,9,0,0,0,10,0,10),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width/1.5

eoc7K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# eoc7K

# Index of Antagonism (Reaction types)
net_rt = net_rt[,1:3]
net_rt$Fun_ID = paste(net_rt$Plug_ID, substr(net_rt$Plate_ID,1,2), sep="")
net_rt$PH_ID = substr(net_rt$Plate_ID,3,3)

ffc_n_pair$PH_ID = substr(ffc_n_pair$pair_ID,4,4)
ffc_n_pair$Fun_ID = substr(ffc_n_pair$pair_ID,1,3)
ffc_n_pair5 = ffc_n_pair[ffc_n_pair$PH_ID==5,]
ffc_n_pair7 = ffc_n_pair[ffc_n_pair$PH_ID==7,]
# reaction type pH 5
rt_netval_5 = net_rt[net_rt$PH_ID==5,] %>% 
  dplyr::group_by(Fun_ID) %>% 
  dplyr::summarise(IOA = sum(RT))
rt_netval_5 = left_join(rt_netval_5, ffc_n_pair5[,c(2,4)])
rt_netval_5$width = rt_netval_5$IOA/rt_netval_5$nfun
rt_netval_5$Fun = toupper(substr(rt_netval_5$Fun_ID,1,1))

value_rt5 = rep(1,5)
for (x in 1:5) {
  value_rt5[x] = sum(unlist(rt_netval_5$width[rt_netval_5$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_rt5, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(1.2,1,0.8,2.6,0,0,0,0,1,4.5,2,1.9,1,3.8,2,1,0.2,3,1,0.8),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*2

rt5 = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# rt5

# reaction type pH 7
rt_netval_7 = net_rt[net_rt$PH_ID==7,] %>% 
  dplyr::group_by(Fun_ID) %>% 
  dplyr::summarise(IOA = sum(RT))
rt_netval_7 = left_join(rt_netval_7, ffc_n_pair7[,c(2,4)])
rt_netval_7$width = rt_netval_7$IOA/rt_netval_7$nfun
rt_netval_7$Fun = toupper(substr(rt_netval_7$Fun_ID,1,1))

value_rt7 = rep(1,5)
for (x in 1:5) {
  value_rt7[x] = sum(unlist(rt_netval_7$width[rt_netval_7$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_rt7, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(1.3,1.7,0.1,2.2,0,0,0,1,1.7,3.3,1.3,1,2.1,2,1.3,1,0.4,3,1,1),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*2

rt7 = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# rt7

# export network plots as png files
visExport(sin5r, type = "png")
visExport(sin5K, type = "png")
visExport(sin7r, type = "png")
visExport(sin7K, type = "png")
visExport(cont5r, type = "png")
visExport(cont7r, type = "png")
visExport(cont5K, type = "png")
visExport(cont7K, type = "png")
visExport(eoc5r, type = "png")
visExport(eoc7r, type = "png")
visExport(eoc5K, type = "png")
visExport(eoc7K, type = "png")
visExport(rt5, type = "png")
visExport(rt7, type = "png")
```

#Phylogeny Plots
```{r phylo}
# Phylogeny used for distance calculations
FFC_nexbay$tip.label = c("Laccaria bicolor","Hebeloma cylindrosporum","Amanita muscaria","Paxillus involutus","Cenococcum geophilum")
FFC_nexbay$node.label = c("",""," 1"," 1")
# png("phyloplot.png", width = 1500, height = 1000, res = 200)
plot.phylo(FFC_nexbay, show.node.label = TRUE)
axisPhylo()

# phylogenetic distances for each pairing
distbay = data.frame(pair_ID = c("CA","CH","CL","CP","HA","HP","LA","LH","LP","PA"), 
                  dist = c(0.6632,0.69,0.649,0.464,0.434,0.498,0.393,0.205,0.457,0.471)) 

# Prepare data
final_data_phylo = final_data_eoc[final_data_eoc$cont_ID==0,]
final_data_phylo = final_data_phylo[,c(1,5,7,8,19,20)]

# Add svs control r/K mean values
summ_r = summarySE(final_data_sin, "r", c("Fun_ID","PH_ID"), na.rm = TRUE)
summ_r = summ_r[,c(1,2,4)]
summ_r$PH_ID = as.character(summ_r$PH_ID)

summ_K = summarySE(final_data_sin, "K", c("Fun_ID","PH_ID"), na.rm = TRUE)
summ_K = summ_K[,c(1,2,4)]
summ_K$PH_ID = as.character(summ_K$PH_ID)

final_data_phylo$PH_ID = substr(final_data_phylo$Plug_ID,4,4)
final_data_phylo$Treat_ID = substr(final_data_phylo$Plug_ID,2,4)
final_data_phylo$pair_ID = substr(final_data_phylo$Plug_ID,2,3)
final_data_phylo$Fun_ID = toupper(substr(final_data_phylo$Plug_ID,1,1))
# final_data_phylo1 = left_join(final_data_phylo, dist)
# final_data_phylo1 = left_join(final_data_phylo1, summ_r, by = c("Fun_ID", "PH_ID"))
# final_data_phylo1 = left_join(final_data_phylo1, summ_K, by = c("Fun_ID", "PH_ID"))
# colnames(final_data_phylo1)[3] = c("r")
# colnames(final_data_phylo1)[4] = c("K")
# colnames(final_data_phylo1)[12] = c("cont_rmean")
# colnames(final_data_phylo1)[13] = c("cont_Kmean")

final_data_phylobay = left_join(final_data_phylo, distbay)
final_data_phylobay = left_join(final_data_phylobay, summ_r, by = c("Fun_ID", "PH_ID"))
final_data_phylobay = left_join(final_data_phylobay, summ_K, by = c("Fun_ID", "PH_ID"))
colnames(final_data_phylobay)[3] = c("r")
colnames(final_data_phylobay)[4] = c("K")
colnames(final_data_phylobay)[12] = c("cont_rmean")
colnames(final_data_phylobay)[13] = c("cont_Kmean")

# calculate rdist
final_data_rdist = final_data_eoc[final_data_eoc$cont_ID=="v",]
final_data_rdist$Treat_ID = substr(final_data_rdist$Plate_ID, 1, 3)
final_data_rdist5 = final_data_rdist[final_data_rdist$PH_ID==5,]
final_data_rdist7 = final_data_rdist[final_data_rdist$PH_ID==7,]

rdist5Tuk = TukeyHSD(aov(lm(r~Treat_ID, data = final_data_rdist5)))
rdist5Tuk = as.data.frame(rdist5Tuk[1])
rdist5Tuk$Treat_ID.diff = abs(rdist5Tuk$Treat_ID.diff)
rdist5Tuk$Treat_ID = c("CA5","HA5","LA5","PA5","CH5","CL5","CP5","LH5","HP5","LP5")
rdist5Tuk = rdist5Tuk[c(5,1,4)]

rdist7Tuk = TukeyHSD(aov(lm(r~Treat_ID, data = final_data_rdist7)))
rdist7Tuk = as.data.frame(rdist7Tuk[1])
rdist7Tuk$Treat_ID.diff = abs(rdist7Tuk$Treat_ID.diff)
rdist7Tuk$Treat_ID = c("CA7","HA7","LA7","PA7","CH7","CL7","CP7","LH7","HP7","LP7")
rdist7Tuk = rdist7Tuk[c(5,1,4)]

rdistTuk = rbind(rdist5Tuk, rdist7Tuk)
colnames(rdistTuk) = c("Treat_ID","rdiff","rp.adj")

final_data_phylodiff = final_data_phylobay
final_data_phylodiff = left_join(final_data_phylodiff, rdistTuk)

# calculate Kdist
final_data_Kdist = final_data_eoc[final_data_eoc$cont_ID=="v",]
final_data_Kdist$Treat_ID = substr(final_data_Kdist$Plate_ID, 1, 3)
final_data_Kdist5 = final_data_Kdist[final_data_Kdist$PH_ID==5,]
final_data_Kdist7 = final_data_Kdist[final_data_Kdist$PH_ID==7,]

Kdist5Tuk = TukeyHSD(aov(lm(K~Treat_ID, data = final_data_Kdist5)))
Kdist5Tuk = as.data.frame(Kdist5Tuk[1])
Kdist5Tuk$Treat_ID.diff = abs(Kdist5Tuk$Treat_ID.diff)
Kdist5Tuk$Treat_ID = c("CA5","HA5","LA5","PA5","CH5","CL5","CP5","LH5","HP5","LP5")
Kdist5Tuk = Kdist5Tuk[c(5,1,4)]

Kdist7Tuk = TukeyHSD(aov(lm(K~Treat_ID, data = final_data_Kdist7)))
Kdist7Tuk = as.data.frame(Kdist7Tuk[1])
Kdist7Tuk$Treat_ID.diff = abs(Kdist7Tuk$Treat_ID.diff)
Kdist7Tuk$Treat_ID = c("CA7","HA7","LA7","PA7","CH7","CL7","CP7","LH7","HP7","LP7")
Kdist7Tuk = Kdist7Tuk[c(5,1,4)]

KdistTuk = rbind(Kdist5Tuk, Kdist7Tuk)
colnames(KdistTuk) = c("Treat_ID","Kdiff","Kp.adj")
final_data_phylodiff = left_join(final_data_phylodiff, KdistTuk, by = c("Treat_ID"))


# linear models growth measures vs phylo dist
mod_dist_r = lm(dist ~ rdiff * PH_ID, data = final_data_phylodiff)
summary(mod_dist_r)

mod_dist_K = lm(dist ~ Kdiff * PH_ID, data = final_data_phylodiff)
summary(mod_dist_K)


# linear mixed effect models
# for r
# mod_EOCr_r = lmer(log(mean_r) ~ cont_rmean * PH_ID + (1|Fun_ID) + (1|Plate_ID), data = final_data_phylodiff)
# summary(mod_EOCr_r)
# class(mod_EOCr_r) = "lmerMod"
# r.squaredGLMM(mod_EOCr_r)
# EOCr_r = as.data.frame(r.squaredGLMM(mod_EOCr_r))
# EOCr_r_R2 = round(EOCr_r$R2c,4)

# mod_EOCr_dist = lmer(log(mean_r) ~ dist * PH_ID + (1|Fun_ID) + (1|Plate_ID), data = final_data_phylodiff)
# summary(mod_EOCr_dist)
# class(mod_EOCr_dist) = "lmerMod"
# r.squaredGLMM(mod_EOCr_dist)
# EOCr_dist = as.data.frame(r.squaredGLMM(mod_EOCr_dist))
# EOCr_dist_R2 = round(EOCr_dist$R2c,4)

mod_EOCr_distbay = lmer(log(mean_r) ~ dist * PH_ID + (1|Fun_ID) + (1|Plate_ID), data = final_data_phylobay)
summary(mod_EOCr_distbay)
class(mod_EOCr_distbay) = "lmerMod"
r.squaredGLMM(mod_EOCr_distbay)
EOCr_distbay = as.data.frame(r.squaredGLMM(mod_EOCr_distbay))
EOCr_distbay_R2 = round(EOCr_distbay$R2c,4)

mod_EOCr_rdiff = lmer(log(mean_r) ~ rdiff * PH_ID + (1|Fun_ID) + (1|Plate_ID), data = final_data_phylodiff)
summary(mod_EOCr_rdiff)
class(mod_EOCr_rdiff) = "lmerMod"
r.squaredGLMM(mod_EOCr_rdiff)
EOCr_rdiff = as.data.frame(r.squaredGLMM(mod_EOCr_rdiff))
EOCr_r_R2diff = round(EOCr_rdiff$R2c,4)

mod_EOC_all = lmer(log(mean_r) ~ rdiff + dist * PH_ID + (1|Fun_ID) + (1|Plate_ID), data = final_data_phylodiff)
summary(mod_EOC_all)
class(mod_EOC_all) = "lmerMod"
r.squaredGLMM(mod_EOC_all)
EOC_all = as.data.frame(r.squaredGLMM(mod_EOC_all))
EOC_all_R2 = round(EOC_all$R2c,4)

# for K
# mod_EOCK_K = lmer(mean_K ~ cont_Kmean * PH_ID + (1|Fun_ID) + (1|Plate_ID), data = final_data_phylodiff)
# summary(mod_EOCK_K)
# class(mod_EOCK_K) = "lmerMod"
# r.squaredGLMM(mod_EOCK_K)
# EOCK_K = as.data.frame(r.squaredGLMM(mod_EOCK_K))
# EOCK_K_R2 = round(EOCK_K$R2c,4)

mod_EOCK_dist = lmer(mean_K ~ dist * PH_ID + (1|Fun_ID) + (1|Plate_ID), data = final_data_phylodiff)
summary(mod_EOCK_dist)
class(mod_EOCK_dist) = "lmerMod"
r.squaredGLMM(mod_EOCK_dist)
EOCK_dist = as.data.frame(r.squaredGLMM(mod_EOCK_dist))
EOCK_dist_R2 = round(EOCK_dist$R2c,4)

mod_EOCK_Kdiff = lmer(mean_K ~ Kdiff * PH_ID + (1|Fun_ID) + (1|Plate_ID), data = final_data_phylodiff)
summary(mod_EOCK_Kdiff)
class(mod_EOCK_Kdiff) = "lmerMod"
r.squaredGLMM(mod_EOCK_Kdiff)
EOCK_Kdiff = as.data.frame(r.squaredGLMM(mod_EOCK_Kdiff))
EOCK_K_R2diff = round(EOCK_Kdiff$R2c,4)


# stargazer tables
# for linear models
stargazer(mod_dist_r, mod_dist_K,
  type = "text",
  # out = "mod_dist_rK.htm",
  dep.var.labels = c("Phylogenetic Distance"),
  column.labels = c("Growth Rate (r)", "Colony Size (K)"),
  covariate.labels = c("Control r diff", "Control K diff", "pH 7", "Control r diff:pH 7", "Control K diff:pH 7", "Constant"),
  summary = TRUE,
  digits = 3
)

#for r
# stargazer(mod_EOCr_r, mod_EOCr_distbay,
#   type = "text",
#   # out = "mod_EOCr.htm",
#   dep.var.labels = c("EOCr"),
#   covariate.labels = c("Growth Rate", "Phylogenetic Distance", "pH 7", "constant"),
#   column.labels = c("Trait-based", "Phylogeny-based"),
#   add.lines = list(c("Conditional pseudo-R2", EOCr_r_R2, EOCr_dist_R2)),
#   summary = TRUE,
#   digits = 3
# )

stargazer(mod_EOCr_rdiff, mod_EOCr_distbay,
  type = "text",
  # out = "mod_EOCrdiff_distbay.htm",
  dep.var.labels = c("EoC"),
  covariate.labels = c("Growth Rate Distance", "Phylogenetic Distance", "pH 7", "Growth Rate Distance:pH 7", "Phylogenetic Distance:pH 7", "Constant"),
  column.labels = c("Growth Rate-based", "Phylogenetic-based"),
  add.lines = list(c("Conditional pseudo-R2", EOCr_r_R2diff, EOCr_dist_R2)),
  summary = TRUE,
  star.cutoffs = c(0.05,0.01,0.001),
  digits = 3
)

stargazer(mod_EOCr_rdiff, mod_EOCr_distbay, mod_EOC_all,
  type = "text",
  # out = "mod_EOCrdiff_dist.htm",
  dep.var.labels = c("EOCr"),
  # covariate.labels = c("Growth Rate Distance", "Phylogenetic Distance", "pH 7", "constant"),
  column.labels = c("Trait-based", "Phylogeny-based", "Both"),
  add.lines = list(c("Conditional pseudo-R2", EOCr_r_R2diff, EOCr_dist_R2, EOC_all_R2)),
  summary = TRUE,
  digits = 3
)

# for K
# stargazer(mod_EOCK_K, mod_EOCK_dist,
#   type = "text",
#   # out = "mod_EOCK.htm",
#   dep.var.labels = c("EOCK"),
#   covariate.labels = c("Colony size", "Phylogenetic Distance", "pH 7", "constant"),
#   column.labels = c("Trait-based", "Phylogeny-based"),
#   add.lines = list(c("Conditional pseudo-R2", EOCK_K_R2, EOCK_dist_R2)),
#   summary = TRUE,
#   digits = 3
# )

stargazer(mod_EOCK_Kdiff, mod_EOCK_dist,
  type = "text",
  # out = "mod_EOCKdiff_dist.htm",
  dep.var.labels = c("EOCK"),
  covariate.labels = c("Colony Size Distance", "Phylogenetic Distance", "pH 7", "constant"),
  column.labels = c("Trait-based", "Phylogeny-based"),
  add.lines = list(c("Conditional pseudo-R2", EOCK_K_R2diff, EOCK_dist_R2)),
  summary = TRUE,
  digits = 3
)

# graphs for linear models
pred_dist_r = ggpredict(mod_dist_r, terms = c("rdiff", "PH_ID"))
plot_dist_r = ggplot(pred_dist_r) + 
  geom_line(aes(x = x, y = predicted, color = group)) +          # slope
  geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
              alpha = 0.2) +  # error band
  geom_point(data = final_data_phylodiff,                      # adding the raw data 
             aes(x = rdiff, y = dist, color = PH_ID)) + 
  labs(x = "control growth rate diff", y = "dist") + 
  theme_cowplot() +
  theme(plot.background = element_rect(fill = "white"))
# ggsave("plot_dist_r.png")

pred_dist_K = ggpredict(mod_dist_K, terms = c("Kdiff", "PH_ID"))
plot_dist_K = ggplot(pred_dist_K) + 
  geom_line(aes(x = x, y = predicted, color = group)) +          # slope
  geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
              alpha = 0.2) +  # error band
  geom_point(data = final_data_phylodiff,                      # adding the raw data 
             aes(x = Kdiff, y = dist, color = PH_ID)) + 
  labs(x = "control colony size difference", y = "dist") + 
  theme_cowplot() +
  theme(plot.background = element_rect(fill = "white"))
# ggsave("plot_dist_K.png")

# graphing the linear mixed effect models
# for r
# pred_EOCr_r = ggpredict(mod_EOCr_r, terms = c("cont_rmean", "PH_ID"))
# plot_EOCr_r = ggplot(pred_EOCr_r) + 
#   geom_line(aes(x = x, y = predicted, color = group)) +          # slope
#   geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
#               alpha = 0.2) +  # error band
#   geom_point(data = final_data_phylo,                      # adding the raw data 
#               aes(x = cont_rmean, y = mean_r, color = PH_ID)) + 
#   labs(x = "control growth rate", y = "EoC_r") + 
#   theme_cowplot() +
#   theme(plot.background = element_rect(fill = "white"))
# # ggsave("plot_EOCr_r.png")

# pred_EOCr_dist = ggpredict(mod_EOCr_dist, terms = c("dist", "PH_ID"), back.transform = FALSE)
# plot_EOCr_dist = ggplot(pred_EOCr_dist) + 
#   geom_line(aes(x = x, y = predicted, color = group)) +          # slope
#   geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
#               alpha = 0.2) +  # error band
#   geom_point(data = final_data_phylo1,                      # adding the raw data 
#               aes(x = dist, y = log(mean_r), color = PH_ID)) + 
#   labs(x = "dist", y = "log(EoC_r)") + 
#   theme_cowplot() +
#   theme(plot.background = element_rect(fill = "white"))
# # ggsave("plot_EOCr_dist.png")

pred_EOCr_distbay = ggpredict(mod_EOCr_distbay, terms = c("dist", "PH_ID"), back.transform = FALSE)
plot_EOCr_distbay = ggplot(pred_EOCr_distbay) + 
  geom_line(aes(x = x, y = predicted, color = group)) +          # slope
  geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
              alpha = 0.2) +  # error band
  geom_point(data = final_data_phylobay,                      # adding the raw data 
              aes(x = dist, y = log(mean_r), color = PH_ID)) + 
  labs(x = "phylogenetic distance", y = "log(EoC)") + 
  theme_cowplot() +
  theme(plot.background = element_rect(fill = "white"), legend.position = "none")
# ggsave("plot_EOCr_distbay.png")

pred_EOCr_rdiff = ggpredict(mod_EOCr_rdiff, terms = c("rdiff", "PH_ID"), back.transform = FALSE)
plot_EOCr_rdiff = ggplot(pred_EOCr_rdiff) + 
  geom_line(aes(x = x, y = predicted, color = group)) +          # slope
  geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
              alpha = 0.2) +  # error band
  geom_point(data = final_data_phylodiff,                      # adding the raw data 
             aes(x = rdiff, y = log(mean_r), color = PH_ID)) + 
  labs(x = "growth rate distance", y = "log(EoC)") + 
  theme_cowplot() +
  theme(plot.background = element_rect(fill = "white"), legend.position = "none")
# ggsave("plot_EOCr_rdiff.png")

# for K
pred_EOCK_K = ggpredict(mod_EOCK_K, terms = c("cont_Kmean", "PH_ID"))
plot_EOCK_K = ggplot(pred_EOCK_K) + 
  geom_line(aes(x = x, y = predicted, color = group)) +          # slope
  geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
              alpha = 0.2) +  # error band
  geom_point(data = final_data_phylo,                      # adding the raw data 
              aes(x = cont_Kmean, y = mean_K, color = PH_ID)) + 
  labs(x = "control colony size", y = "EoC_K") + 
  theme_cowplot() +
  theme(plot.background = element_rect(fill = "white"))
# ggsave("plot_EOCK_K.png")

pred_EOCK_dist = ggpredict(mod_EOCK_dist, terms = c("dist", "PH_ID"))
plot_EOCK_dist = ggplot(pred_EOCK_dist) + 
  geom_line(aes(x = x, y = predicted, color = group)) +          # slope
  geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
              alpha = 0.2) +  # error band
  geom_point(data = final_data_phylo,                      # adding the raw data 
              aes(x = dist, y = mean_K, color = PH_ID)) + 
  labs(x = "dist", y = "EoC_K") + 
  theme_cowplot() +
  theme(plot.background = element_rect(fill = "white"))
# ggsave("plot_EOCK_dist.png")

pred_EOCK_Kdiff = ggpredict(mod_EOCK_Kdiff, terms = c("Kdiff", "PH_ID"))
plot_EOCK_Kdiff = ggplot(pred_EOCK_Kdiff) + 
  geom_line(aes(x = x, y = predicted, color = group)) +          # slope
  geom_ribbon(aes(x = x, ymin = predicted - std.error, ymax = predicted + std.error, fill = group), 
              alpha = 0.2) +  # error band
  geom_point(data = final_data_phylodiff,                      # adding the raw data 
             aes(x = Kdiff, y = mean_K, color = PH_ID)) + 
  labs(x = "colony size dist", y = "EoC_K") + 
  theme_cowplot() +
  theme(plot.background = element_rect(fill = "white"))
# ggsave("plot_EOCK_Kdiff.png")

plot_dist_r
# plot_EOCr_r
plot_EOCr_rdiff
# plot_EOCr_dist
plot_EOCr_distbay
# plot_EOCr_distrax
plot_dist_K
# plot_EOCK_K
plot_EOCK_Kdiff
# plot_EOCK_dist

```