---
title: "Network"
output: html_document
date: '2022-07-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Rmisc)
library(tidyverse)
library(cowplot)
library(visNetwork)
library(ape)
library(ggpubr)
library(lme4)
library(lmerTest)
library(MuMIn)
library(emmeans)
library(stargazer)
library(ggeffects)
library(svglite)

# read in data
final_data = read_csv("~/FungalFightClub/finaldata1.csv")
final_data_sin = final_data[final_data$cont_ID=="s",]
final_data_eoc = read_csv("~/FungalFightClub/final_data_eoc.csv")
final_data_eoc$PH_ID = as.character(final_data_eoc$PH_ID) # to fix code
final_data_eoc$Plug_ID = substr(final_data_eoc$Plug_ID,1,4) # to fix code
Tuk_sin_fin = read_csv("~/FungalFightClub/Tuk_sin_fin.csv")
Tuk_geoc_fin = read_csv("~/FungalFightclub/Tuk_geoc_fin.csv")
Tuk_final = read_csv("~/FungalFightClub/Tuk_final.csv")
sig_svs_fin = read_csv("~/FungalFightClub/sig_svs_fin.csv")
sig_eoc_fin = read_csv("~/FungalFightClub/sig_eoc_fin.csv")
net_rt = read_csv("~/FungalFightClub/FFC Treatments - Reaction Types.csv")
FFC_nex = read.nexus("~/FungalFightClub/infile.nex.con.tre")
FFC_nexbay = read.nexus("~/FungalFightClub/mrBayesPost.nex")
FFC_nexrax = read.nexus("~/FungalFightClub/RAxML_Tree.nex")
ffc_n_pair = read_csv("~/FungalFightClub/ffc_n_pair.csv")

# constants
fungi = c("A","C","H","L","P")
pH = c(5,7)
value = c("r","K")

# labels
labs = data.frame(main=c("(a) Amanita muscaria","(b) Cenococcum geophilum","(c) Hebeloma cylindrosporum","(d) Laccaria bicolor","(e) Paxillus involutus"), letter=c("(a)","(b)","(c)","(d)","(e)"), nams=c("A. muscaria","C. geophilum","H. cylindrosporum","L. bicolor","P. involutus"), x=c(-0.055,-0.0725,-0.0775,-0.05,-0.055), y=c(1,1,1,1,1))

# color palette
palette = c("#EC8FA3", "#FCBA65", "#FAECCF", "#8D7F99", "#8C9D57")
```

#Network Plots
```{r net, fig.height=7, fig.width=7}
# get control data ready for comparison to other controls
final_data_sinp = final_data_sin[,c(1:4,7,8)]
final_data_sinp = gather(final_data_sinp, "key", "value", -Plate_ID, -Fun_ID, -cont_ID, -PH_ID)
final_data_sinp$PH_ID = as.factor(final_data_sinp$PH_ID)
final_data_sin1 = final_data_sinp %>% 
  spread(key = key, value = value)
final_data_sin1$Treat_ID = substr(final_data_sin1$Plate_ID,1,3)
final_data_sin1 = final_data_sin1 %>% 
  dplyr::group_by(Treat_ID) %>%
  dplyr::summarise(mean_r = mean(r, na.rm=TRUE), mean_K = mean(K, na.rm=TRUE)) %>% 
  dplyr::mutate(PH_ID = substr(Treat_ID,3,3), Fun_ID = substr(Treat_ID,1,1))
final_data_sin5 = final_data_sin1[final_data_sin1$PH_ID==5,]
final_data_sin7 = final_data_sin1[final_data_sin1$PH_ID==7,]

final_data_svs = final_data_eoc[final_data_eoc$cont_ID=="v",]
final_data_svs$Treat_ID = substr(final_data_svs$Plate_ID,1,3)
final_data_svs = final_data_svs %>% 
  dplyr::group_by(Treat_ID) %>% 
  dplyr::summarise(mean_r = mean(r, na.rm=TRUE), mean_K = mean(K, na.rm=TRUE)) %>% 
  dplyr::mutate(PH_ID = substr(Treat_ID,3,3), Fun_ID = substr(Treat_ID,1,1))
final_data_svs5 = final_data_svs[final_data_svs$PH_ID==5,]
final_data_svs7 = final_data_svs[final_data_svs$PH_ID==7,]

# set up a df for storing network control values
contpairfin = as.data.frame(matrix(nrow=25,ncol=2))
colnames(contpairfin) = c("Fun", "opp")
contpairfin$Fun = c(rep("A",5),rep("C",5),rep("H",5),rep("L",5),rep("P",5))
contpairfin$opp = c(rep(c("A","C","H","L","P"),5))
contpairfin = contpairfin[contpairfin$Fun!=contpairfin$opp,]
contpairfin5 = contpairfin
contpairfin7 = contpairfin
contsinfin5 = contpairfin
contsinfin7 = contpairfin

# calculate the control comparison (which will be the width of network lines)
for (x in 1:nrow(contsinfin5)) {
  contsinfin5$width_r[x] = (final_data_sin5[final_data_sin5$Fun_ID==contsinfin5$Fun[x],"mean_r"])/(final_data_sin5[final_data_sin5$Fun_ID==contsinfin5$opp[x],"mean_r"])
  contsinfin5$width_K[x] = (final_data_sin5[final_data_sin5$Fun_ID==contsinfin5$Fun[x],"mean_K"])/(final_data_sin5[final_data_sin5$Fun_ID==contsinfin5$opp[x],"mean_K"])
}
value_cs5r = rep(1,5)
value_cs5K = rep(1,5)
for (x in 1:5) {
  value_cs5r[x] = sum(unlist(contsinfin5$width_r[contsinfin5$Fun==fungi[x]]))
  value_cs5K[x] = sum(unlist(contsinfin5$width_K[contsinfin5$Fun==fungi[x]]))
}

for (x in 1:nrow(contsinfin7)) {
  contsinfin7$width_r[x] = (final_data_sin7[final_data_sin7$Fun_ID==contsinfin7$Fun[x],"mean_r"])/(final_data_sin7[final_data_sin7$Fun_ID==contsinfin7$opp[x],"mean_r"])
  contsinfin7$width_K[x] = (final_data_sin7[final_data_sin7$Fun_ID==contsinfin7$Fun[x],"mean_K"])/(final_data_sin7[final_data_sin7$Fun_ID==contsinfin7$opp[x],"mean_K"])
}
value_cs7r = rep(1,5)
value_cs7K = rep(1,5)
for (x in 1:5) {
  value_cs7r[x] = sum(unlist(contsinfin7$width_r[contsinfin7$Fun==fungi[x]]))
  value_cs7K[x] = sum(unlist(contsinfin7$width_K[contsinfin7$Fun==fungi[x]]))
}

for (x in 1:nrow(contpairfin5)) {
  contpairfin5$width_r[x] = (final_data_svs5[final_data_svs5$Fun_ID==contpairfin5$Fun[x],"mean_r"])/(final_data_svs5[final_data_svs5$Fun_ID==contpairfin5$opp[x],"mean_r"])
  contpairfin5$width_K[x] = (final_data_svs5[final_data_svs5$Fun_ID==contpairfin5$Fun[x],"mean_K"])/(final_data_svs5[final_data_svs5$Fun_ID==contpairfin5$opp[x],"mean_K"])
}
value_cp5r = rep(1,5)
value_cp5K = rep(1,5)
for (x in 1:5) {
  value_cp5r[x] = sum(unlist(contpairfin5$width_r[contpairfin5$Fun==fungi[x]]))
  value_cp5K[x] = sum(unlist(contpairfin5$width_K[contpairfin5$Fun==fungi[x]]))
}

for (x in 1:nrow(contpairfin7)) {
  contpairfin7$width_r[x] = (final_data_svs7[final_data_svs7$Fun_ID==contpairfin7$Fun[x],"mean_r"])/(final_data_svs7[final_data_svs7$Fun_ID==contpairfin7$opp[x],"mean_r"])
  contpairfin7$width_K[x] = (final_data_svs7[final_data_svs7$Fun_ID==contpairfin7$Fun[x],"mean_K"])/(final_data_svs7[final_data_svs7$Fun_ID==contpairfin7$opp[x],"mean_K"])
}
value_cp7r = rep(1,5)
value_cp7K = rep(1,5)
for (x in 1:5) {
  value_cp7r[x] = sum(unlist(contpairfin7$width_r[contpairfin7$Fun==fungi[x]]))
  value_cp7K[x] = sum(unlist(contpairfin7$width_K[contpairfin7$Fun==fungi[x]]))
}

# network of sin controls pH 5 for r
nodes = data.frame(id = 1:5, value = value_cs5r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contsinfin5$width_r),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

sin5r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# sin5r

# network of sin controls pH 7 for r
nodes = data.frame(id = 1:5, value = value_cs7r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contsinfin7$width_r),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

sin7r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# sin7r

# network of sin controls pH 5 for K
nodes = data.frame(id = 1:5, value = value_cs5K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contsinfin5$width_K),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

sin5K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# sin5K

# network of sin controls pH 7 for K
nodes = data.frame(id = 1:5, value = value_cs7K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contsinfin7$width_K),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

sin7K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# sin7K

# network of svs controls pH 5 for r
nodes = data.frame(id = 1:5, value = value_cp5r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contpairfin5$width_r),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

cont5r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# cont5r

# network of svs controls pH 7 for r
nodes = data.frame(id = 1:5, value = value_cp7r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contpairfin7$width_r),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

cont7r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# cont7r

# network of svs controls pH 5 for K
nodes = data.frame(id = 1:5, value = value_cp5K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contpairfin5$width_K),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

cont5K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# cont5K

# network of svs controls pH 7 for K
nodes = data.frame(id = 1:5, value = value_cp7K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width = unlist(contpairfin7$width_K),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*3

cont7K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# cont7K

# eoc wins
eocnetwin = final_data_eoc[final_data_eoc$cont_ID==0,] %>% 
  dplyr::group_by(Plate_ID) %>% 
  dplyr::mutate(eocrwin = Plug_ID[which.max(mean_r)],
                eocKwin = Plug_ID[which.max(mean_K)])

eocnetwinr = as.data.frame(base::table(eocnetwin[eocnetwin$cont_ID==0,"eocrwin"]))
eocnetwinK = as.data.frame(base::table(eocnetwin[eocnetwin$cont_ID==0,"eocKwin"]))
eocnetwinr$Freq = eocnetwinr$Freq/2
eocnetwinK$Freq = eocnetwinK$Freq/2
eocnetwinr$PH = substr(eocnetwinr$Var1,4,4)
eocnetwinK$PH = substr(eocnetwinK$Var1,4,4)
eocnetwinr$Fun = toupper(substr(eocnetwinr$Var1,1,1))
eocnetwinK$Fun = toupper(substr(eocnetwinK$Var1,1,1))


# eoc 5 r
eoc5rfin = eocnetwinr[eocnetwinr$PH==5,]
value_e5r = rep(1,5)
for (x in 1:5) {
  value_e5r[x] = sum(unlist(eoc5rfin$Freq[eoc5rfin$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_e5r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(0,4,6,10,10,8,5,8,6,0,10,6,4,0,0,2,0,1,4,8),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width/1.5

eoc5r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# eoc5r

# eoc 7 r
eoc7rfin = eocnetwinr[eocnetwinr$PH==7,]
value_e7r = rep(1,5)
for (x in 1:5) {
  value_e7r[x] = sum(unlist(eoc7rfin$Freq[eoc7rfin$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_e7r, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(5,6,9,10,4,9,9,10,0,0,1,1,0,0,7,8,0,0,9,2),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width/1.5

eoc7r = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# eoc7r

# eoc 5 K
eoc5Kfin = eocnetwinK[eocnetwinK$PH==5,]
value_e5K = rep(1,5)
for (x in 1:5) {
  value_e5K[x] = sum(unlist(eoc5Kfin$Freq[eoc5Kfin$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_e5K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(7,1,4,9,3,7,4,0,9,1,10,3,6,1,0,2,1,9,7,8),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width/1.5

eoc5K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# eoc5K

# eoc 7 K
eoc7Kfin = eocnetwinK[eocnetwinK$PH==7,]
value_e7K = rep(1,5)
for (x in 1:5) {
  value_e7K[x] = sum(unlist(eoc7Kfin$Freq[eoc7Kfin$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_e7K, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(9,0,1,10,0,0,0,0,6,9,8,10,8,9,0,0,0,10,0,10),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width/1.5

eoc7K = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# eoc7K

# Index of Antagonism (Reaction types)
net_rt = net_rt[,1:3]
net_rt$Fun_ID = paste(net_rt$Plug_ID, substr(net_rt$Plate_ID,1,2), sep="")
net_rt$PH_ID = substr(net_rt$Plate_ID,3,3)

ffc_n_pair$PH_ID = substr(ffc_n_pair$pair_ID,4,4)
ffc_n_pair$Fun_ID = substr(ffc_n_pair$pair_ID,1,3)
ffc_n_pair5 = ffc_n_pair[ffc_n_pair$PH_ID==5,]
ffc_n_pair7 = ffc_n_pair[ffc_n_pair$PH_ID==7,]
# reaction type pH 5
rt_netval_5 = net_rt[net_rt$PH_ID==5,] %>% 
  dplyr::group_by(Fun_ID) %>% 
  dplyr::summarise(IOA = sum(RT))
rt_netval_5 = left_join(rt_netval_5, ffc_n_pair5[,c(2,4)])
rt_netval_5$width = rt_netval_5$IOA/rt_netval_5$nfun
rt_netval_5$Fun = toupper(substr(rt_netval_5$Fun_ID,1,1))

value_rt5 = rep(1,5)
for (x in 1:5) {
  value_rt5[x] = sum(unlist(rt_netval_5$width[rt_netval_5$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_rt5, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(1.2,1,0.8,2.6,0,0,0,0,1,4.5,2,1.9,1,3.8,2,1,0.2,3,1,0.8),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*2

rt5 = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# rt5

# reaction type pH 7
rt_netval_7 = net_rt[net_rt$PH_ID==7,] %>% 
  dplyr::group_by(Fun_ID) %>% 
  dplyr::summarise(IOA = sum(RT))
rt_netval_7 = left_join(rt_netval_7, ffc_n_pair7[,c(2,4)])
rt_netval_7$width = rt_netval_7$IOA/rt_netval_7$nfun
rt_netval_7$Fun = toupper(substr(rt_netval_7$Fun_ID,1,1))

value_rt7 = rep(1,5)
for (x in 1:5) {
  value_rt7[x] = sum(unlist(rt_netval_7$width[rt_netval_7$Fun==fungi[x]]))
}

nodes = data.frame(id = 1:5, value = value_rt7, label = c("A","C","H","L","P"), group = c("A","C","H","L","P"), font.size = c(20,20,20,20,20))
edges = data.frame(from = c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5), 
                   to = c(2,3,4,5,1,3,4,5,1,2,4,5,1,2,3,5,1,2,3,4), 
                   width= c(1.3,1.7,0.1,2.2,0,0,0,1,1.7,3.3,1.3,1,2.1,2,1.3,1,0.4,3,1,1),
                   smooth = c(FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE), 
                   length = c(rep(300, 20)),
                   arrows = c(rep("to", 20)))
edges$width = edges$width*2

rt7 = visNetwork(nodes, edges, width = "100%", height = 500) %>%
  visGroups(groupname = "A", color = palette[4]) %>% 
  visGroups(groupname = "C", color = palette[5]) %>% 
  visGroups(groupname = "H", color = palette[2]) %>% 
  visGroups(groupname = "L", color = palette[1]) %>% 
  visGroups(groupname = "P", color = palette[3]) %>%
  visLayout(randomSeed = 22)
# rt7

# export network plots as pdf files
visExport(sin5r, type = "png")
# visExport(sin5K, type = "pdf")
visExport(sin7r, type = "pdf")
# visExport(sin7K, type = "pdf")
visExport(cont5r, type = "pdf")
visExport(cont7r, type = "pdf")
# visExport(cont5K, type = "pdf")
# visExport(cont7K, type = "pdf")
visExport(eoc5r, type = "pdf")
visExport(eoc7r, type = "pdf")
# visExport(eoc5K, type = "pdf")
# visExport(eoc7K, type = "pdf")
visExport(rt5, type = "pdf")
visExport(rt7, type = "pdf")
```
